<파이썬 코드 레시피> 코드 수정 제안
moseskim/python-recipe-src pull request #4
Opened 2021-12-27 12:54 UTC by srorien

교정 과정에서 발견한, 샘플 코드 수정 필요한 부분들입니다, 확인 부탁합니다.

2021-12-28 12:21 UTC, moseskim requested changes
@srorien 님 
다음 파일들은 샘플 파일이 아닌 생성된 파일이므로 제거해주세요. 
이후에 마스터에 병합하겠습니다 :)
(txt 파일은 제가 삭제를 할 수 있는데, 바이너리는 삭제를 못하네요 ㅠ)

- `src/218/sample.zip`
- `src/218/sample2.zip`
- `src/220/sample.tar.gz`

2021-12-29 03:08 UTC, srorien commented
> @srorien 님 다음 파일들은 샘플 파일이 아닌 생성된 파일이므로 제거해주세요. 이후에 마스터에 병합하겠습니다 :) (txt 파일은 제가 삭제를 할 수 있는데, 바이너리는 삭제를 못하네요 ㅠ)
> 
> * `src/218/sample.zip`
> * `src/218/sample2.zip`
> * `src/220/sample.tar.gz`

@moseskim 님, 말씀하신 3개 파일 제거했습니다(샘플 코드를 에러 없이 실행하고자 로컬에서 임의로 만들어 썼던 파일들입니다 ㅠ) 나머지도 확인 후 병합 잘 부탁드립니다!

2021-12-29 23:50 UTC, moseskim approved these changes
확인했습니다. 감사합니다 ^^

2021-12-29 23:50 UTC, moseskim commented
@srorien 더 추가하실 내용 없으시면 머지하겠습니다 ^^

2021-12-30 00:08 UTC, srorien commented
> @srorien 더 추가하실 내용 없으시면 머지하겠습니다 ^^

@moseskim 네, 어제 1교 끝났습니다, 머지 부탁드려요 ^^ 2교 이후 진행하다가 혹시 더 보이면 pr드릴게요~ 고맙습니다!

2022-01-11 23:12 UTC, merged